### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kpennell**

### CODE REVIEW

**Comment by chmac** [comment]
@kpennell Thanks for the PR.

What’s the motivation behind this change? Does the `import ...` syntax not work in the default Gatsby setup? Do you know if something has changed there, or did this never work?

I’m not opposed to merging your PR, just wondering what the motivation is behind it. I’m assuming the `import ...` syntax used to work, but maybe I’m wrong there.

**Comment by kpennell** [comment]
Didn't work for me

**Comment by chmac** [comment]
@kpennell What starter were you using? The [default starter](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/components/header.js) uses `import...` syntax, so I assume it usually works. We could add a second example that adds the `require ...` syntax as well, maybe that’s the best solution, what do you think?

**Comment by chmac** [comment]
Closing this assuming it's no longer active, feel free to reopen if I misunderstood...

**Pull request closed without merging**
